import { Candidate, Job, Message, CandidateRankAuditItem, BiasAuditSummary, DemoStep } from './types';

export const INITIAL_CANDIDATE: Candidate = {
  id: 'cand-arjun-01',
  name: 'Arjun Kumar',
  headline: 'Certified Practical Electrical Technician',
  trade: 'Electrical & Motor Maintenance',
  avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
  location: 'Chandigarh, Punjab',
  overallConfidence: 84,
  experienceYears: 3,
  languages: ['pa', 'hi', 'en'],
  phone: '+91 98765 43210',
  email: 'arjun.tech.verify@equipath.internal',
  bio: 'Hands-on electrical technician with 3 years of rigorous practical field experience in 3-phase induction motors, panel rewiring, industrial fault troubleshooting, and industrial safety compliance.',
  badges: [
    '✓ Scenario Verified',
    '✓ Safety First Certified',
    '✓ Multilingual Assessed (Punjabi/Hindi)',
    '✓ Top 5% Troubleshooting Speed',
  ],
  skills: [
    {
      name: 'Electrical Wiring',
      category: 'Electrical',
      confidenceScore: 88,
      assessmentsCount: 5,
      lastAssessed: '2026-08-20',
      status: 'verified',
      breakdown: { technical: 90, troubleshooting: 86, safety: 92, practicalReasoning: 84 },
      evidenceSummary: 'Successfully diagnosed 3-phase wiring phase imbalance and correctly applied lock-out/tag-out protocol in live simulation.',
    },
    {
      name: 'Troubleshooting',
      category: 'Diagnostics',
      confidenceScore: 84,
      assessmentsCount: 6,
      lastAssessed: '2026-08-21',
      status: 'verified',
      breakdown: { technical: 86, troubleshooting: 88, safety: 90, practicalReasoning: 82 },
      evidenceSummary: 'Demonstrated rapid root-cause isolation for motor capacitor failure and stator overheating in Punjabi voice assessment.',
    },
    {
      name: 'Safety Procedures',
      category: 'Compliance',
      confidenceScore: 93,
      assessmentsCount: 7,
      lastAssessed: '2026-08-22',
      status: 'verified',
      breakdown: { technical: 92, troubleshooting: 89, safety: 98, practicalReasoning: 93 },
      evidenceSummary: 'Consistently checked for residual voltage discharge, de-energization confirmation, and PPE verification before testing.',
    },
    {
      name: 'Motor Repair',
      category: 'Machinery',
      confidenceScore: 79,
      assessmentsCount: 4,
      lastAssessed: '2026-08-19',
      status: 'verified',
      breakdown: { technical: 82, troubleshooting: 78, safety: 86, practicalReasoning: 74 },
      evidenceSummary: 'Accurately articulated bearing inspection, winding resistance measurement with multimeter, and thermal overload reset logic.',
    },
    {
      name: 'Equipment Maintenance',
      category: 'Maintenance',
      confidenceScore: 71,
      assessmentsCount: 3,
      lastAssessed: '2026-08-18',
      status: 'verified',
      breakdown: { technical: 74, troubleshooting: 70, safety: 80, practicalReasoning: 68 },
      evidenceSummary: 'Completed routine inspection checklist simulations for distribution boards and emergency generator transfer switches.',
    },
    {
      name: 'Earthing & Grounding',
      category: 'Safety',
      confidenceScore: 86,
      assessmentsCount: 4,
      lastAssessed: '2026-08-21',
      status: 'verified',
      breakdown: { technical: 88, troubleshooting: 84, safety: 94, practicalReasoning: 82 },
      evidenceSummary: 'Verified Earth Pit resistance measurement protocol and neutral-to-earth voltage leakage troubleshooting.',
    },
  ],
  completedAssessments: [
    {
      id: 'eval-001',
      questionId: 'q-motor-01',
      questionText: 'ਇੱਕ ਮੋਟਰ ਜ਼ਿਆਦਾ ਗਰਮ ਹੋ ਰਹੀ ਹੈ ਭਾਵੇਂ ਵੋਲਟੇਜ ਆਮ ਹੈ। ਤੁਸੀਂ ਸਭ ਤੋਂ ਪਹਿਲਾਂ ਕੀ ਚੈੱਕ ਕਰੋਗੇ?',
      answerText: 'ਮੈਂ ਪਹਿਲਾਂ motor ਦੀ winding resistance ਅਤੇ bearing check ਕਰਾਂਗਾ, ਅਤੇ ਇਹ ਦੇਖਾਂਗਾ ਕਿ cooling fan ਜਾਮ ਤਾਂ ਨਹੀਂ ਹੋਇਆ। ਨਾਲ ਹੀ power isolate ਕਰਕੇ multi-meter ਨਾਲ earth leakage ਚੈੱਕ ਕਰਾਂਗਾ।',
      isVoice: true,
      audioDurationSeconds: 8,
      transcript: 'ਮੈਂ ਪਹਿਲਾਂ motor ਦੀ winding ਅਤੇ bearing check ਕਰਾਂਗਾ...',
      language: 'pa',
      translatedText: 'I would first check the motor winding resistance and bearing condition, and ensure the cooling fan is not jammed. Also isolate power and check for earth leakage with a multimeter.',
      scores: {
        technicalScore: 88,
        keyPointScore: 22,
        reasoningScore: 82,
        safetyScore: 91,
        specificityScore: 79,
        overallScore: 87,
      },
      assessmentConfidence: 87,
      strengths: [
        'Identified winding resistance as primary thermal fault factor',
        'Explicitly mentioned power isolation safety step before touching terminal box',
        'Suggested mechanical bearing inspection alongside electrical diagnostics',
      ],
      weaknesses: [
        'Could have explicitly mentioned checking ambient ventilation temperature',
      ],
      feedback: 'The candidate demonstrated strong practical knowledge of electrical motor thermal failure modes with an immediate safety-first mindset.',
      nextDifficulty: 'Advanced',
      safetyPointsAddressed: ['Power isolation', 'Multimeter insulation check', 'De-energized testing'],
      expectedConceptsMet: ['Winding resistance', 'Bearing friction', 'Cooling obstruction', 'Earth leakage'],
      evaluatedAt: '2026-08-22T10:15:00Z',
    },
  ],
  references: [
    {
      id: 'ref-01',
      name: 'Harpreet Singh',
      role: 'Chief Site Supervisor',
      company: 'Punjab Power & Industrial Works',
      relationship: 'Direct Supervisor (2023 - 2025)',
      quote: 'Worked with Arjun for 2 years. Strong troubleshooting ability, extremely disciplined with safety lockouts, and reliable on high-pressure field repairs.',
      rating: 5,
      verifiedAt: '2026-07-15',
      status: 'verified',
    },
    {
      id: 'ref-02',
      name: 'Kuldeep Verma',
      role: 'Workshop Lead',
      company: 'Verma Electric & Rewinding',
      relationship: 'Senior Colleague (2022 - 2023)',
      quote: 'Arjun learned rewinding and motor overhaul in record time. His intuition for spotting burnt coils and bearing wear by sound is exceptional.',
      rating: 5,
      verifiedAt: '2026-06-10',
      status: 'verified',
    },
  ],
};

export const MOCK_CANDIDATES: CandidateRankAuditItem[] = [
  {
    id: 'cand-001',
    candidateName: 'Priya Sharma',
    trade: 'Industrial Automation & Wiring',
    experienceYears: 4,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    beforeRank: 1,
    beforeScore: 94,
    beforeSignals: {
      employmentGapPenalty: 0,
      collegeTierBonus: 8,
      resumePrestigeBonus: 8,
      languagePenalty: 0,
      verifiedSkillsContribution: 42,
      experienceContribution: 24,
    },
    afterRank: 1,
    afterScore: 95,
    afterSignals: {
      verifiedSkillsContribution: 46,
      experienceContribution: 26,
      assessmentEvidenceContribution: 19,
      jobRequirementsContribution: 4,
      nonJobRelevantSignalsRemoved: 0,
    },
    status: 'Strong Match',
    keyEvidence: 'PLC ladder logic debugging and 440V panel isolation certified.',
    languages: ['en', 'hi'],
  },
  {
    id: 'cand-arjun-01',
    candidateName: 'Arjun Kumar',
    trade: 'Electrical & Motor Maintenance',
    experienceYears: 3,
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
    beforeRank: 7,
    beforeScore: 78,
    beforeSignals: {
      employmentGapPenalty: -12, // penalised for lack of continuous formal corporate payroll
      collegeTierBonus: 0,       // No tier 1 college
      resumePrestigeBonus: 0,    // No resume branding
      languagePenalty: -6,       // Assessed in Punjabi/Hindi instead of English CV
      verifiedSkillsContribution: 44,
      experienceContribution: 22,
    },
    afterRank: 2,
    afterScore: 91,
    afterSignals: {
      verifiedSkillsContribution: 45,
      experienceContribution: 25,
      assessmentEvidenceContribution: 18,
      jobRequirementsContribution: 3,
      nonJobRelevantSignalsRemoved: 18,
    },
    status: 'Strong Match',
    keyEvidence: 'Verified in 3-phase motor overhaul, 93% safety score, 88% wiring proficiency.',
    languages: ['pa', 'hi', 'en'],
  },
  {
    id: 'cand-003',
    candidateName: 'Simran Kaur',
    trade: 'HVAC & Commercial Refrigeration',
    experienceYears: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    beforeRank: 2,
    beforeScore: 92,
    beforeSignals: {
      employmentGapPenalty: 0,
      collegeTierBonus: 4,
      resumePrestigeBonus: 5,
      languagePenalty: 0,
      verifiedSkillsContribution: 43,
      experienceContribution: 25,
    },
    afterRank: 3,
    afterScore: 90,
    afterSignals: {
      verifiedSkillsContribution: 44,
      experienceContribution: 25,
      assessmentEvidenceContribution: 17,
      jobRequirementsContribution: 4,
      nonJobRelevantSignalsRemoved: 0,
    },
    status: 'Strong Match',
    keyEvidence: 'Chiller compressor fault diagnosis and EPA refrigerant recovery protocol.',
    languages: ['pa', 'en', 'hi'],
  },
  {
    id: 'cand-004',
    candidateName: 'Rahul Singh',
    trade: 'Appliance & Transformer Tech',
    experienceYears: 2,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    beforeRank: 4,
    beforeScore: 82,
    beforeSignals: {
      employmentGapPenalty: 0,
      collegeTierBonus: 6,
      resumePrestigeBonus: 4,
      languagePenalty: 0,
      verifiedSkillsContribution: 38,
      experienceContribution: 18,
    },
    afterRank: 4,
    afterScore: 83,
    afterSignals: {
      verifiedSkillsContribution: 40,
      experienceContribution: 20,
      assessmentEvidenceContribution: 19,
      jobRequirementsContribution: 4,
      nonJobRelevantSignalsRemoved: 0,
    },
    status: 'Review',
    keyEvidence: 'Step-down transformer rewinding and domestic appliance relay testing.',
    languages: ['hi', 'en'],
  },
  {
    id: 'cand-005',
    candidateName: 'Aman Verma',
    trade: 'Industrial Welding & Fabrication',
    experienceYears: 4,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    beforeRank: 5,
    beforeScore: 81,
    beforeSignals: {
      employmentGapPenalty: -4,
      collegeTierBonus: 0,
      resumePrestigeBonus: 2,
      languagePenalty: -2,
      verifiedSkillsContribution: 42,
      experienceContribution: 23,
    },
    afterRank: 5,
    afterScore: 85,
    afterSignals: {
      verifiedSkillsContribution: 43,
      experienceContribution: 24,
      assessmentEvidenceContribution: 15,
      jobRequirementsContribution: 3,
      nonJobRelevantSignalsRemoved: 6,
    },
    status: 'Qualified',
    keyEvidence: 'TIG/MIG pipe welding pressure leak test 99% airtight benchmark.',
    languages: ['hi', 'en'],
  },
  {
    id: 'cand-006',
    candidateName: 'Harpreet Singh',
    trade: 'Senior Electrical Supervisor',
    experienceYears: 7,
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    beforeRank: 3,
    beforeScore: 89,
    beforeSignals: {
      employmentGapPenalty: 0,
      collegeTierBonus: 3,
      resumePrestigeBonus: 6,
      languagePenalty: 0,
      verifiedSkillsContribution: 41,
      experienceContribution: 28,
    },
    afterRank: 6,
    afterScore: 82,
    afterSignals: {
      verifiedSkillsContribution: 38,
      experienceContribution: 28,
      assessmentEvidenceContribution: 13,
      jobRequirementsContribution: 3,
      nonJobRelevantSignalsRemoved: 0,
    },
    status: 'Review',
    keyEvidence: 'High-voltage substation lockouts, HT switchgear maintenance.',
    languages: ['pa', 'hi', 'en'],
  },
  {
    id: 'cand-007',
    candidateName: 'Neha Gupta',
    trade: 'Power Plant Control Assistant',
    experienceYears: 2,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    beforeRank: 6,
    beforeScore: 80,
    beforeSignals: {
      employmentGapPenalty: 0,
      collegeTierBonus: 5,
      resumePrestigeBonus: 5,
      languagePenalty: 0,
      verifiedSkillsContribution: 35,
      experienceContribution: 16,
    },
    afterRank: 7,
    afterScore: 79,
    afterSignals: {
      verifiedSkillsContribution: 36,
      experienceContribution: 18,
      assessmentEvidenceContribution: 21,
      jobRequirementsContribution: 4,
      nonJobRelevantSignalsRemoved: 0,
    },
    status: 'Review',
    keyEvidence: 'Digital relay calibrations and generator frequency balancing.',
    languages: ['en', 'hi'],
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001',
    title: 'Electrical Technician',
    company: 'BrightCore Services',
    location: 'Chandigarh, Punjab',
    type: 'Full-time',
    salaryRange: '₹25,000–₹32,000/month',
    requiredSkills: ['Electrical Wiring', 'Troubleshooting', 'Safety Procedures', 'Motor Repair'],
    preferredExperienceYears: 2,
    description: 'Looking for a hands-on technician to maintain industrial manufacturing machinery, diagnose 3-phase power faults, and execute safety maintenance protocols.',
    responsibilities: [
      'Perform root-cause diagnostics on AC induction motors and circuit breakers',
      'Execute monthly preventive maintenance and earthing resistance tests',
      'Follow stringent Lock-Out / Tag-Out (LOTO) protocols during all panel work',
    ],
    urgency: 'Immediate',
    postedDate: '2 days ago',
    matchScoreForArjun: {
      skillsScore: 45,
      experienceScore: 25,
      evidenceScore: 18,
      locationScore: 4,
      totalMatch: 92,
    },
  },
  {
    id: 'job-002',
    title: 'Maintenance Technician',
    company: 'Apex Industrial Corp',
    location: 'Mohali, Punjab',
    type: 'Full-time',
    salaryRange: '₹24,000–₹30,000/month',
    requiredSkills: ['Equipment Maintenance', 'Electrical Wiring', 'Troubleshooting'],
    preferredExperienceYears: 2,
    description: 'Provide daily maintenance support for high-throughput packaging machinery and electrical distribution boards.',
    responsibilities: [
      'Maintain conveyor belt electrical drives and sensor arrays',
      'Inspect panel breakers, capacitors, and contactors for thermal degradation',
    ],
    urgency: 'Immediate',
    postedDate: '3 days ago',
    matchScoreForArjun: {
      skillsScore: 42,
      experienceScore: 25,
      evidenceScore: 16,
      locationScore: 5,
      totalMatch: 88,
    },
  },
  {
    id: 'job-003',
    title: 'Field Electrician',
    company: 'Metro Power Systems',
    location: 'Ludhiana, Punjab',
    type: 'Full-time',
    salaryRange: '₹26,000–₹34,000/month',
    requiredSkills: ['Electrical Wiring', 'Earthing & Grounding', 'Safety Procedures'],
    preferredExperienceYears: 3,
    description: 'Execute commercial solar and grid inverter installations, field grounding tests, and distribution cable laying.',
    responsibilities: [
      'Conduct earth pit resistance and ground fault checks',
      'Troubleshoot inverter AC/DC phase imbalances',
    ],
    urgency: 'Regular',
    postedDate: '1 week ago',
    matchScoreForArjun: {
      skillsScore: 44,
      experienceScore: 25,
      evidenceScore: 17,
      locationScore: 3,
      totalMatch: 89,
    },
  },
  {
    id: 'job-004',
    title: 'Motor Repair Specialist',
    company: 'Punjab Rewinding Works',
    location: 'Jalandhar, Punjab',
    type: 'Full-time',
    salaryRange: '₹28,000–₹35,000/month',
    requiredSkills: ['Motor Repair', 'Troubleshooting', 'Electrical Wiring'],
    preferredExperienceYears: 3,
    description: 'Specialize in stator winding repair, bearing replacement, rotor balancing, and dynamic load testing for pump and industrial motors.',
    responsibilities: [
      'Strip, rewind, and varnish burnt 3-phase motor stators',
      'Test winding insulation resistance using megohmmeter (Megger)',
    ],
    urgency: 'Immediate',
    postedDate: 'Just now',
    matchScoreForArjun: {
      skillsScore: 41,
      experienceScore: 25,
      evidenceScore: 18,
      locationScore: 3,
      totalMatch: 87,
    },
  },
  {
    id: 'job-005',
    title: 'HVAC Technician',
    company: 'CoolWave Climate Systems',
    location: 'Chandigarh, Punjab',
    type: 'Full-time',
    salaryRange: '₹27,000–₹33,000/month',
    requiredSkills: ['HVAC Maintenance', 'Troubleshooting', 'Electrical Wiring'],
    preferredExperienceYears: 2,
    description: 'Diagnose and service commercial VRF units, ductable air conditioning, and thermostat electrical circuitry.',
    responsibilities: [
      'Check refrigerant levels and compressor contactors',
      'Troubleshoot electrical blower motor capacitor faults',
    ],
    urgency: 'Regular',
    postedDate: '4 days ago',
    matchScoreForArjun: {
      skillsScore: 34,
      experienceScore: 25,
      evidenceScore: 14,
      locationScore: 4,
      totalMatch: 77,
    },
  },
  {
    id: 'job-006',
    title: 'Machine Technician',
    company: 'Precision Automations Ltd',
    location: 'Panchkula, Haryana',
    type: 'Full-time',
    salaryRange: '₹25,000–₹31,000/month',
    requiredSkills: ['Equipment Maintenance', 'Troubleshooting', 'Safety Procedures'],
    preferredExperienceYears: 2,
    description: 'Operate and maintain automated hydraulic and pneumatic stamping machines with electrical interlocks.',
    responsibilities: [
      'Inspect pneumatic solenoid valves and optical safety light curtains',
      'Perform scheduled lubrication and electrical relay tests',
    ],
    urgency: 'Regular',
    postedDate: '5 days ago',
    matchScoreForArjun: {
      skillsScore: 38,
      experienceScore: 25,
      evidenceScore: 15,
      locationScore: 4,
      totalMatch: 82,
    },
  },
  {
    id: 'job-007',
    title: 'Appliance Repair Technician',
    company: 'QuickFix Home Solutions',
    location: 'Chandigarh, Punjab',
    type: 'Full-time',
    salaryRange: '₹22,000–₹28,000/month',
    requiredSkills: ['Troubleshooting', 'Electrical Wiring', 'Appliance Repair'],
    preferredExperienceYears: 1,
    description: 'Door-to-door diagnostic and repair service for domestic inverters, washing machines, microwaves, and water purifiers.',
    responsibilities: [
      'Diagnose PCB relay and thermal fuse failures',
      'Explain repair quotes and safety measures transparently to homeowners',
    ],
    urgency: 'Immediate',
    postedDate: '6 days ago',
    matchScoreForArjun: {
      skillsScore: 40,
      experienceScore: 25,
      evidenceScore: 16,
      locationScore: 4,
      totalMatch: 85,
    },
  },
  {
    id: 'job-008',
    title: 'Workshop Technician',
    company: 'Northern Engineering Works',
    location: 'Ambala, Haryana',
    type: 'Full-time',
    salaryRange: '₹23,000–₹29,000/month',
    requiredSkills: ['Equipment Maintenance', 'Motor Repair', 'Safety Procedures'],
    preferredExperienceYears: 2,
    description: 'Maintain shop floor power tools, lathe electrical control boxes, and overhead gantry cranes.',
    responsibilities: [
      'Maintain pendant push-button crane controls and limit switches',
      'Refurbish drill press and milling machine drive motors',
    ],
    urgency: 'Regular',
    postedDate: '1 week ago',
    matchScoreForArjun: {
      skillsScore: 39,
      experienceScore: 25,
      evidenceScore: 15,
      locationScore: 3,
      totalMatch: 82,
    },
  },
  {
    id: 'job-009',
    title: 'Commercial Plumbing Technician',
    company: 'HydroTech Infrastructure',
    location: 'Chandigarh, Punjab',
    type: 'Full-time',
    salaryRange: '₹24,000–₹30,000/month',
    requiredSkills: ['Plumbing', 'Safety Procedures', 'Equipment Maintenance'],
    preferredExperienceYears: 3,
    description: 'Maintain dual booster pump plumbing systems, fire hydrant pressure regulators, and drainage sumps.',
    responsibilities: [
      'Install industrial backflow preventers and pressure relief valves',
      'Coordinate with electrical team for submersible pump float switch hookups',
    ],
    urgency: 'Regular',
    postedDate: '2 weeks ago',
    matchScoreForArjun: {
      skillsScore: 28,
      experienceScore: 25,
      evidenceScore: 12,
      locationScore: 4,
      totalMatch: 69,
    },
  },
  {
    id: 'job-010',
    title: 'Electrical Maintenance Assistant',
    company: 'Zenith Logistics Hub',
    location: 'Zirakpur, Punjab',
    type: 'Full-time',
    salaryRange: '₹20,000–₹26,000/month',
    requiredSkills: ['Electrical Wiring', 'Safety Procedures'],
    preferredExperienceYears: 1,
    description: 'Assist chief engineer with warehouse LED high-bay lighting, backup generator changeovers, and dock leveler maintenance.',
    responsibilities: [
      'Replace high-bay drivers and inspect industrial plug sockets',
      'Assist with monthly battery bank load test for emergency UPS',
    ],
    urgency: 'Immediate',
    postedDate: '3 days ago',
    matchScoreForArjun: {
      skillsScore: 42,
      experienceScore: 25,
      evidenceScore: 17,
      locationScore: 5,
      totalMatch: 89,
    },
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-01',
    conversationId: 'conv-brightcore-arjun',
    senderId: 'recruiter-brightcore',
    senderName: 'Rohit Sharma (Hiring Lead, BrightCore Services)',
    senderRole: 'recruiter',
    receiverId: 'cand-arjun-01',
    type: 'text',
    text: 'Hi Arjun! We reviewed your verified practical assessment in 3-phase motor troubleshooting and were very impressed with your safety isolation protocol score (93%). We would love to discuss the Electrical Technician position with our field operations team.',
    timestamp: '2026-08-22T14:30:00Z',
    isRead: true,
  },
  {
    id: 'msg-02',
    conversationId: 'conv-brightcore-arjun',
    senderId: 'recruiter-brightcore',
    senderName: 'Rohit Sharma (Hiring Lead, BrightCore Services)',
    senderRole: 'recruiter',
    receiverId: 'cand-arjun-01',
    type: 'interview_invite',
    text: 'Interview invitation for Electrical Technician (₹25,000–₹32,000/mo)',
    timestamp: '2026-08-22T14:32:00Z',
    isRead: true,
    interviewDetails: {
      jobTitle: 'Electrical Technician',
      proposedTime: 'Tomorrow at 11:00 AM IST',
      location: 'BrightCore Facility, Industrial Area Phase 2, Chandigarh',
      accepted: false,
    },
  },
  {
    id: 'msg-03',
    conversationId: 'conv-brightcore-arjun',
    senderId: 'cand-arjun-01',
    senderName: 'Arjun Kumar',
    senderRole: 'candidate',
    receiverId: 'recruiter-brightcore',
    type: 'voice',
    audioDuration: 9,
    language: 'pa',
    transcript: 'ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ ਰੋਹਿਤ ਜੀ, ਸੁਨੇਹੇ ਲਈ ਧੰਨਵਾਦ। ਮੈਂ ਕੱਲ੍ਹ 11 ਵਜੇ ਇੰਟਰਵਿਊ ਲਈ ਆਉਣ ਲਈ ਤਿਆਰ ਹਾਂ।',
    translatedTranscript: 'Sat Sri Akal Rohit ji, thank you for the message. I am ready to come for the interview tomorrow at 11:00 AM.',
    timestamp: '2026-08-22T14:45:00Z',
    isRead: true,
  },
];

export const DEFAULT_AUDIT_SUMMARY: BiasAuditSummary = {
  jobId: 'job-001',
  jobTitle: 'Electrical Technician (BrightCore Services)',
  totalApplicants: 128,
  signalsRemoved: [
    'Employment Gap History (-12 pts)',
    'College / Institute Tier (+8 pts)',
    'Formal Resume Brand Prestige (+8 pts)',
    'Language / Accent Bias (-6 pts for Hindi/Punjabi native audio)',
  ],
  signalsPreserved: [
    'Verified Hands-on Technical Skills (+45 pts)',
    'Demonstrated Practical Experience (+25 pts)',
    'Scenario Assessment Evidence (+18 pts)',
    'Job Specific Requirements (+4 pts)',
  ],
  averageRankShift: 4.2,
  underrepresentedBoostPercentage: 68,
  disclaimer: 'Ranking Transparency Audit is an explainable decision support tool. EquiPath provides data-driven evidence; the human recruiter retains full autonomy and makes the final hiring decision.',
};

export const DEMO_STEPS: DemoStep[] = [
  {
    stepNumber: 1,
    title: 'Step 1: Select Trade Skill',
    description: 'Candidate starts by choosing their hands-on trade without needing a resume or degree.',
    targetView: 'candidate-claim',
    actionPrompt: 'Select "Electrical Troubleshooting" and see trade options.',
  },
  {
    stepNumber: 2,
    title: 'Step 2: Choose Language Preference',
    description: 'EquiPath supports Punjabi, Hindi, and English natively so language is never a barrier.',
    targetView: 'candidate-claim',
    actionPrompt: 'Select Punjabi (ਪੰਜਾਬੀ) or Hindi as the primary assessment language.',
  },
  {
    stepNumber: 3,
    title: 'Step 3: Dynamic Scenario Generation',
    description: 'System dynamically synthesizes a realistic, un-rehearsed practical scenario using controlled blueprint parameters.',
    targetView: 'candidate-verify',
    actionPrompt: 'Observe the generated scenario: Motor Overheating & Voltage Diagnosis.',
  },
  {
    stepNumber: 4,
    title: 'Step 4: Voice Assessment Option',
    description: 'Skilled workers can answer naturally using voice recording rather than typing complex text.',
    targetView: 'candidate-verify',
    actionPrompt: 'Click "🎙 Answer by Voice" to begin recording.',
  },
  {
    stepNumber: 5,
    title: 'Step 5: Voice Recording & Waveform',
    description: 'Candidate speaks in native Punjabi. Live audio waveform and recording timer provide intuitive feedback.',
    targetView: 'candidate-verify',
    actionPrompt: 'Watch the live waveform animation and timer.',
  },
  {
    stepNumber: 6,
    title: 'Step 6: Native Script Transcription',
    description: 'Speech-to-text generates the transcript in original Gurmukhi Punjabi script.',
    targetView: 'candidate-verify',
    actionPrompt: 'View transcript: "ਮੈਂ ਪਹਿਲਾਂ motor ਦੀ winding ਅਤੇ bearing check ਕਰਾਂਗਾ..."',
  },
  {
    stepNumber: 7,
    title: 'Step 7: Transcript Review & Submit',
    description: 'Candidate can edit the transcript if desired before final submission.',
    targetView: 'candidate-verify',
    actionPrompt: 'Click "Submit Answer" for AI evaluation.',
  },
  {
    stepNumber: 8,
    title: 'Step 8: Multidimensional AI Evaluation',
    description: 'AI evaluates the native Punjabi response directly across Technical Knowledge, Reasoning, Safety, and Specificity.',
    targetView: 'candidate-verify',
    actionPrompt: 'View assessment breakdown: Technical (88%), Reasoning (82%), Safety (91%), Confidence (87%).',
  },
  {
    stepNumber: 9,
    title: 'Step 9: Adaptive Follow-up Generation',
    description: 'Because the candidate scored >80%, the system escalates difficulty to Intermediate/Advanced and asks a deep follow-up.',
    targetView: 'candidate-verify',
    actionPrompt: 'See follow-up: "Why would you check the winding, and what multimeter reading indicates a fault?"',
  },
  {
    stepNumber: 10,
    title: 'Step 10: Complete Second Scenario',
    description: 'Candidate submits follow-up response demonstrating deep practical diagnostics.',
    targetView: 'candidate-verify',
    actionPrompt: 'Submit follow-up response to solidify verified status.',
  },
  {
    stepNumber: 11,
    title: 'Step 11: Update Assessment Confidence',
    description: 'Overall skill confidence rises with transparent evidence notes.',
    targetView: 'candidate-verify',
    actionPrompt: 'Check updated confidence score: 87/100.',
  },
  {
    stepNumber: 12,
    title: 'Step 12: Verified Skill Profile Generated',
    description: 'Arjun receives a verified profile backed by audio recordings, peer references, and confidence metrics.',
    targetView: 'candidate-profile',
    actionPrompt: 'View Arjun Kumar\'s public verified skill badge and peer reference from Harpreet Singh.',
  },
  {
    stepNumber: 13,
    title: 'Step 13: Review Verified Skills Summary',
    description: 'Skills verified: Electrical Wiring (88%), Troubleshooting (84%), Safety Procedures (93%).',
    targetView: 'candidate-profile',
    actionPrompt: 'Inspect skill breakdown cards and evidence summaries.',
  },
  {
    stepNumber: 14,
    title: 'Step 14: Explainable Job Matching',
    description: 'Candidate matched with BrightCore Services Electrical Technician at 92% match score with explainable components.',
    targetView: 'candidate-jobs',
    actionPrompt: 'Click match pill to see +45 Skills, +25 Exp, +18 Evidence, +4 Location.',
  },
  {
    stepNumber: 15,
    title: 'Step 15: Switch to Recruiter View',
    description: 'Recruiter logs into the pipeline dashboard for the Electrical Technician job opening.',
    targetView: 'recruiter-dashboard',
    actionPrompt: 'Notice 128 applicants and 47 verified candidates.',
  },
  {
    stepNumber: 16,
    title: 'Step 16: Traditional Candidate Ranking (Baseline)',
    description: 'Under traditional screening, Arjun Kumar is ranked #7 (78%) due to employment gap penalties and lack of resume prestige.',
    targetView: 'recruiter-bias-audit',
    actionPrompt: 'Observe Arjun at Rank #7 in the candidate table.',
  },
  {
    stepNumber: 17,
    title: 'Step 17: Run Ranking Transparency Audit',
    description: 'Recruiter triggers the Transparency Audit to remove non-job-relevant signals.',
    targetView: 'recruiter-bias-audit',
    actionPrompt: 'Click [ Run Fairness Audit ] button to execute live recalculation.',
  },
  {
    stepNumber: 18,
    title: 'Step 18: Dramatic Rank Transition (#7 → #2)',
    description: 'Watch cards animate! Arjun Kumar leaps from Rank #7 to Rank #2 with a 91% verified skill score.',
    targetView: 'recruiter-bias-audit',
    actionPrompt: 'Observe the visual #7 → #2 badge and rank recalculation.',
  },
  {
    stepNumber: 19,
    title: 'Step 19: Transparency & Evidence Audit',
    description: 'Recruiter inspects why the rank shifted and listens to Arjun\'s original audio answer with verified safety notes.',
    targetView: 'recruiter-bias-audit',
    actionPrompt: 'Review the audit signal diff chart and listen to Arjun\'s Punjabi voice note.',
  },
  {
    stepNumber: 20,
    title: 'Step 20: Recruiter Messages Candidate & Requests Interview',
    description: 'Recruiter immediately sends an interview invitation and message to Arjun Kumar.',
    targetView: 'recruiter-messages',
    actionPrompt: 'Send interview invitation to complete the skills-first hiring loop.',
  },
];
